export const EVENT_POSTER_WIDTH = 720;
export const EVENT_POSTER_HEIGHT = 900;
export const EVENT_POSTER_RATIO = EVENT_POSTER_WIDTH / EVENT_POSTER_HEIGHT;
export const EVENT_POSTER_PICKER_ASPECT = [4, 5];

export const TICKET_CANVAS_WIDTH = 720;
export const TICKET_CANVAS_HEIGHT = 1800;
export const TICKET_CANVAS_RATIO = TICKET_CANVAS_WIDTH / TICKET_CANVAS_HEIGHT;

export const TICKET_PREVIEW_WIDTH = 392;
export const TICKET_PREVIEW_HEIGHT = Math.round(
  TICKET_PREVIEW_WIDTH / TICKET_CANVAS_RATIO,
);
