export const EVENT_POSTER_WIDTH = 720;
export const EVENT_POSTER_HEIGHT = 900;
export const EVENT_POSTER_RATIO = EVENT_POSTER_WIDTH / EVENT_POSTER_HEIGHT;
export const EVENT_POSTER_PICKER_ASPECT = [4, 5];
